### ISSUE TITLE
Supported browsers and responsiveness

### ISSUE THREAD

**Issue by procmail** [hongkhanh/gridify#1]
Hi,

I just came across your plugin, and it looks really suitable for my projects.

Any idea if it's responsive, and what browsers it works on?

Thanks!

**Comment by hongkhanh** [comment]
Hi,

For responsive webpage, you just specify max_width for the item. I think gridify can work on any browser. However, if you want animation, your browser must support CSS3. Let me know if you have any issue with the plugin.

Cheers,
