### ISSUE TITLE
Could not place cross button and title over the image

### ISSUE THREAD

**Issue by changeweb** [hongkhanh/gridify#3]
I'm using Handlebars.js template. Gridify only works for

```
 <div class="grid">
  {{#each img in images}}
   <img {{bind-attr src=img.src_path}}>
  {{/each}}
 </div>
```

But when I tried to use `<span>` for cross button, gridify doesn't allow the spans over images.

```
<div class="grid">
   {{#each img in images}}
   <img {{bind-attr src=img.src_path}}>
   <span style="position:absolute;top:0;left:80%;z-index:1;">x</span>
  {{/each}}
 </div>
```

**Comment by hongkhanh** [comment]
Hi, you should put your grid item into a container.

<div class="grid">
   {{#each img in images}}
        <div class="item">
            <img {{bind-attr src=img.src_path}}>
            <span style="position:absolute;top:0;left:80%;z-index:1;">x</span>
        </div>
  {{/each}}
 </div>

**Comment by hongkhanh** [comment]
Hi, you should put your grid item into a container.

<div class="grid">
   {{#each img in images}}
        <div class="item">
            <img {{bind-attr src=img.src_path}}>
            <span
style="position:absolute;top:0;left:80%;z-index:1;">x</span>
        </div>

  {{/each}}
 </div>

**Comment by hongkhanh** [comment]
As you use absolute position inside grid item, you should put it into a
relative container as well.

<div class="grid">
   {{#each img in images}}
        <div class="item">
            <div style="display:relative; width:100%; height:100%">
                <img {{bind-attr src=img.src_path}}>
                <span
style="position:absolute;top:0;left:80%;z-index:1;">x</span>
            </div>

```
    </div>
```

  {{/each}}
 </div>

**Comment by changeweb** [comment]
Not working. All cross is positioned in top:0;left:80%;

**Comment by hongkhanh** [comment]
Gridify only arrange your grid item like pinterest. Basically, you have to create your own style for grid item. You should know how to use relative position and absolute position and absolute position in a relative container.
